routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();



    Route::prefix('admin')->group(function () {
        Route::resource('categorias', 'CategoriaController');
        Route::resource('posts', 'PostController');
        Route::get('/', 'HomeController@index')->name('home');
    });

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
     /**
     * Os atributos que são atribuíveis em massa.
     *
     * @var array
     */
    protected $fillable = [
        'titulo',
        'status',
        'descricao',
        'imagem',
    ];

    /**
     * Protege os campos 'id', 'created_at', 'update_at' de inserções
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'update_at'];

    /**
     * Campos que são datas
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];
    
     /**
     * As categorias que pertencem ao post
     */
    public function categorias()
    {
        return $this->belongsToMany('App\Categoria', 'post_categoria', 'post_id', 'categoria_id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Post;
use App\Categoria;
use App\Http\Requests\PostRequest;

class postController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->query) {
            $posts = Post::where("titulo","LIKE","%{$request->input('query')}%")->orWhere("descricao","LIKE","%{$request->input('query')}%")->paginate(7);
        }else {
            $posts = Post::paginate(7);
        }

        return view('post.index', ['posts' => $posts]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = $this->getCategorias();
        return view('post.create',compact('categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {            
        $post = new Post;
        $post->titulo = $request->titulo;
        $post->status = $request->status;
        $post->descricao = $request->descricao;

        if($request->has('imagem')){
            $file = $request->file('imagem');
            $extension = $file->getClientOriginalExtension(); // recebe a extensão da imagem
            $filename =time().'.'.$extension;
            $file->move('uploads/posts/', $filename);
            $post->imagem = 'uploads/posts/'.$filename;
        }
        $post->save();

        $post->categorias()->sync(
            $request->categorias
        );
        return redirect()->route('posts.index')->with('success', 'post criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {        
        $post = Post::findOrFail($id);
        return view('post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::findOrFail($id);
        $categorias = $this->getCategorias();
        return view('post.edit',compact('post', 'categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, post $post)
    {
        $request->validate([
            'titulo' => 'required',
            'status' => 'required',
            'descricao' => 'required',
        ]);

        $post->titulo = $request->titulo;
        $post->status = $request->status;
        $post->descricao = $request->descricao;

        if($request->has('imagem')){
            $file = $request->file('imagem');
            $extension = $file->getClientOriginalExtension(); // recebe a extensão da imagem
            $filename =time().'.'.$extension;
            $file->move('uploads/posts/', $filename);
            $post->imagem = 'uploads/posts/'.$filename;
        }
        $post->save();

        $post->categorias()->sync(
            $request->categorias
        );

        return redirect()->route('posts.show', $post->id)
                         ->with('success','post atualizado com sucesso!')
                         ->with(['post' => $post]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        return redirect()->route('posts.index')

                        ->with('success','post excluido com sucesso');
        
    }

    public function getCategorias(){
        $categorias = Categoria::where('status', 'ativo')->get();
        return $categorias;
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-6">Adicionar novo Post</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('posts.index') }}"> Ver todos os posts</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {{-- Mostra os erros de validação --}}
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Erro na validação de alguns campos.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    {{-- Formulário para criar nova categoria --}}
                    <form action="{{ route('posts.store') }}" enctype='multipart/form-data' method="POST">
                        @csrf
                        <div class="row">
                            {{-- campo titulo --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Titulo:</strong>
                                    <input type="text" name="titulo" class="form-control" placeholder="Titulo do Post">
                                </div>
                            </div>
                            {{-- campo status --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Status:</strong>
                                <select class="form-control" id="status" name="status">
                                    <option>ativo</option>
                                    <option>inativo</option>
                                </select>
                            </div>
                            </div>
                            {{-- campo categorias --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Categorias:</strong>
                                    <select multiple size="6" class="form-control" id="status" name="categorias[]">
                                        @foreach ($categorias as $categoria)
                                            <option value="{{$categoria->id}}">{{$categoria->titulo}}
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            {{-- campo descrição --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descrição:</strong>
                                    <textarea id="editor" class="form-control" style="height:150px" name="descricao" placeholder="Descrição"></textarea>
                                </div>
                            </div>
                            {{-- campo imagem --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Imagem capa:</strong>
                                    <input type="file" name="imagem" accept="image/*" />
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Salvar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-6">Editar post</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('posts.index') }}"> Ver todos os
                                posts</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {{-- Mostra os erros de validação --}}
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Erro na validação de alguns campos.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    {{-- Formulário para criar nova post --}}
                    <form action="{{ route('posts.update', $post->id) }}" enctype="multipart/form-data" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            {{-- campo titulo --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Titulo:</strong>
                                    <input type="text" name="titulo" value="{{$post->titulo}}" class="form-control" placeholder="Titulo do Post">
                                    </div>
                                </div>
                                {{-- campo status --}}
                                <div class="col-xs-2 col-sm-2 col-md-2">
                                <div class="form-group">
                                    <strong>Status:</strong>
                                    <select name="status" class="form-control" id="status">
                                        @foreach (['ativo', 'inativo'] as $status)
                                            <option value="{{ $status }}"
                                            @if ($status == old('status', $post->status))
                                                selected="selected"
                                            @endif
                                            >{{ $status }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                </div>
                                {{-- campo categorias --}}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Categorias:</strong>
                                        <select multiple size="6" class="form-control" name="categorias[]">
                                            @foreach ($categorias as $categoria)
                                                <option value="{{$categoria->id}}" 
                                                  @foreach ($post->categorias as $Postcategoria)
                                                    @if ($Postcategoria->id == $categoria->id)
                                                    {{'selected="selected"'}}
                                                    @endif 
                                                  @endforeach >
                                                 {{ $categoria->titulo }}</option>               
                                            @endforeach 
                                        </select>                                        
                                    </div>
                                </div>
                                {{-- campo descrição --}}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Descrição:</strong>
                                        <textarea id="editor" class="form-control" style="height:150px" name="descricao" placeholder="Descrição">{{$post->descricao}}</textarea>
                                    </div>
                                </div>
                                {{-- campo imagem --}}
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Imagem capa:</strong>
                                        <input type="file" name="imagem" accept="image/*" />                                                                                
                                    </div>
                                    <div>
                                        @if (file_exists($post->imagem))
                                            <strong>Imagem atual:</strong>  
                                        <img class="card-img-top" src="{{asset($post->imagem)}}" style="width:100px;"> 
                                        @else
                                            {{-- <img class="card-img-top" src="{{asset(default.png)}}">  --}}
                                        @endif 
                                    </div>
                                </div>
                                
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Atualizar</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-4">Posts</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('posts.create') }}"> Criar novo Post</a>
                        </div>
                    </div>                    
                </div>

                <div class="card-body">
                    {{-- Formulário de pesquisa --}}
                    <div class="row justify-content-md-center">
                        <div  class="form-group">
                        <form action="{{ route('posts.index') }}" method="GET" class="form-inline">
                                <div class="form-group mx-sm-3 mb-2">
                                    <input type="text" class="form-control" name="query" placeholder="Pesquise"/>
                                </div>
                                <button type="submit" class="btn btn-primary mb-2">Pesquisar</button>
                            </form>
                        </div>

                    </div>
                    {{-- mostra mensagem quando uma post é criada ou atualiazada com sucesso --}}
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                            
                    <table class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Titulo</th>
                            <th scope="col">Status</th>
                            <th scope="col">Categorias</th>
                            <th scope="col">Descrição</th>
                            <th scope="col">Ações </th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($posts as $post)
                            <tr>
                                <th scope="row">{{$post->id}}</th>
                                <td>{{$post->titulo}} </td>
                                <td>{{$post->status}}</td>
                                <td>
                                    @foreach ($post->categorias as $categoria)
                                        <span class="badge badge-secondary">{{$categoria->titulo}}</span>
                                    @endforeach
                                </td>
                                <td>{{ str_limit($post->descricao, $limit = 50, $end = '...') }}</td>
                                <td>    
                                            <div class="btn-group" role="group" aria-label="Basic example">
                                                <a class="btn btn-primary btn-sm" href="{{ route('posts.show',$post->id) }}">Mostrar</a>
                                                <a class="btn btn-warning btn-sm" href="{{ route('posts.edit',$post->id) }}">Editar</a>
                                             </div>                                                                        
                                                                        
                                </td>
                            </tr> 
                            @endforeach                                                  
                        </tbody>
                      </table>
                      <div class="row justify-content-md-center">
                            {{ $posts->links() }}
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/post/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        {{-- mostra mensagem quando uma post é criada ou atualiazada com sucesso --}}
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif 
    </div>
    <div class="row justify-content-center">            
        <div class="">
            <div class="card" style="width: 30rem;">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col">Detalhe do Post</div>
                        <div class="col">
                            <div class="row">
                                <div class="col-4">
                                    <a class="btn btn-success btn-sm" href="{{ route('posts.index') }}"> Ver todos</a>
                                </div>
                                <div class="col-4">
                                    <a class="btn btn-primary btn-sm" href="{{ route('posts.edit', $post->id) }}"> Editar</a>
                                </div>
                            </div>                            
                        </div>
                    </div>                    
                </div>
                @if (file_exists($post->imagem))
                    <img class="card-img-top" src="{{asset($post->imagem)}}"> 
                @else
                    {{-- <img class="card-img-top" src="{{asset(default.png)}}">  --}}
                @endif                
                {{-- card-body--}}
                <div class="card-body">                                       
                            <div class="row">                               
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <h3>{{ $post->titulo }}</h3>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Status:</strong>
                                        {{ $post->status }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Descrição:</strong>
                                        {{ $post->descricao }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Data Criação:</strong>
                                            {{ $post->created_at->format('d/m/Y h:m:s') }}
                                        </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Data da ultima atualização:</strong>
                                            {{ $post->updated_at->format('d/m/Y h:m:s') }}
                                        </div>
                                </div>
                            </div>
                </div>
                {{-- end card-body --}}
            </div>
        </div>
    </div>
</div>
@endsection