routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});


Auth::routes();



    Route::prefix('admin')->group(function () {
        Route::resource('categorias', 'CategoriaController');
        Route::resource('posts', 'PostController');
        Route::get('/', 'HomeController@index')->name('home');
    });

app/Categoria.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Categoria extends Model
{
     /**
     * Os atributos que são atribuíveis em massa.
     *
     * @var array
     */
    protected $fillable = [
        'titulo',
        'status',
        'descricao',
    ];

    /**
     * Protege os campos 'id', 'created_at', 'update_at' de inserções
     *
     * @var array
     */
    protected $guarded = ['id', 'created_at', 'update_at'];

    /**
     * Campos que são datas
     *
     * @var array
     */
    protected $dates = [
        'created_at',
        'updated_at',
    ];

    /**
     * As postagens que pertencem a categoria
     */

    public function post()
    {
        return $this->belongsToMany('App\Post', 'post_categoria', 'post_id', 'categoria_id');
    }
}

app/Http/Controllers/CategoriaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Categoria;
use App\Http\Requests\CategoriaRequest;

class CategoriaController extends Controller
{
     /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->query) {
            $categorias = Categoria::where("titulo","LIKE","%{$request->input('query')}%")->orWhere("descricao","LIKE","%{$request->input('query')}%")->paginate(7);
        }else {
            $categorias = Categoria::paginate(7);
        }

        return view('categoria.index', ['categorias' => $categorias]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('categoria.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoriaRequest $request)
    {
        Categoria::create($request->all());
        return redirect()->route('categorias.index')->with('success', 'categoria criada com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categoria = Categoria::findOrFail($id);
        return view('categoria.show',compact('categoria'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categoria = Categoria::findOrFail($id);
        return view('categoria.edit',compact('categoria'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categoria $categoria)
    {
        $request->validate([
            'titulo' => 'required',
            'status' => 'required',
        ]);

        $categoria->update($request->all());

        return redirect()->route('categorias.index')
                         ->with('success','Categoria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categoria $categoria)
    {
        $categoria->delete();
        return redirect()->route('categoria.index')

                        ->with('success','Categoria excluida com sucesso');
        
    }
}

resources/views/categoria/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-6">Adicionar nova Categorias</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('categorias.index') }}"> Ver todas as
                                categorias</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {{-- Mostra os erros de validação --}}
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Erro na validação de alguns campos.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    {{-- Formulário para criar nova categoria --}}
                    <form action="{{ route('categorias.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            {{-- campo titulo --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Titulo:</strong>
                                    <input type="text" name="titulo" class="form-control" placeholder="Titulo da Categoria">
                                </div>
                            </div>
                            {{-- campo status --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Status:</strong>
                                <select class="form-control" id="status" name="status">
                                    <option>ativo</option>
                                    <option>inativo</option>
                                </select>
                            </div>
                            </div>
                            {{-- campo descrição --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descrição:</strong>
                                    <textarea class="form-control" style="height:150px" name="descricao" placeholder="Descrição"></textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/categoria/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-6">Adicionar nova Categorias</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('categorias.index') }}"> Ver todas as
                                categorias</a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    {{-- Mostra os erros de validação --}}
                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <strong>Whoops!</strong>Erro na validação de alguns campos.<br><br>
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    {{-- Formulário para editar categoria --}}
                    <form action="{{ route('categorias.update', $categoria->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            {{-- campo titulo --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Titulo:</strong>
                                    <input type="text" name="titulo" value="{{$categoria->titulo}}" class="form-control" placeholder="Titulo da Categoria">
                                </div>
                            </div>
                            {{-- campo status --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                            <div class="form-group">
                                <strong>Status:</strong>
                                <select name="status" class="form-control" id="status">
                                    @foreach (['ativo', 'inativo'] as $status)
                                        <option value="{{ $status }}"
                                        @if ($status == old('status', $categoria->status))
                                            selected="selected"
                                        @endif
                                        >{{ $status }}</option>
                                    @endforeach
                                </select>
                            </div>
                            </div>
                            {{-- campo descrição --}}
                            <div class="col-xs-12 col-sm-12 col-md-12">
                                <div class="form-group">
                                    <strong>Descrição:</strong>
                                    <textarea class="form-control" style="height:150px" name="descricao" placeholder="Descrição">{{$categoria->descricao}}</textarea>
                                </div>
                            </div>
                            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/categoria/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-4">Categorias</div>
                        <div class="col-2">
                            <a class="btn btn-success btn-sm" href="{{ route('categorias.create') }}"> Criar nova Categoria</a>
                        </div>
                    </div>                    
                </div>

                <div class="card-body">
                    {{-- Formulário de pesquisa --}}
                    <div class="row justify-content-md-center">
                            <div  class="form-group">
                            <form action="{{ route('categorias.index') }}" method="GET" class="form-inline">
                                    <div class="form-group mx-sm-3 mb-2">
                                        <input type="text" class="form-control" name="query" placeholder="Pesquise"/>
                                    </div>
                                    <button type="submit" class="btn btn-primary mb-2">Pesquisar</button>
                                </form>
                            </div>
    
                        </div>
                    {{-- mostra mensagem quando uma categoria é criada ou atualiazada com sucesso --}}
                    @if ($message = Session::get('success'))
                        <div class="alert alert-success">
                            <p>{{ $message }}</p>
                        </div>
                    @endif
                            
                    <table class="table table-striped table-bordered">
                        <thead>
                          <tr>
                            <th scope="col">#</th>
                            <th scope="col">Titulo</th>
                            <th scope="col">Status</th>
                            <th scope="col">Descrição</th>
                            <th scope="col">Ações </th>
                          </tr>
                        </thead>
                        <tbody>
                            @foreach ($categorias as $categoria)
                            <tr>
                                <th scope="row">{{$categoria->id}}</th>
                                <td>{{$categoria->titulo}} </td>
                                <td>{{$categoria->status}}</td>
                                <td>{{$categoria->descricao}}</td>
                                <td>    
                                    <div class="btn-group" role="group" aria-label="Basic example">
                                        <a class="btn btn-primary btn-sm" href="{{ route('categorias.show',$categoria->id) }}">Mostrar</a>
                                        <a class="btn btn-warning btn-sm" href="{{ route('categorias.edit',$categoria->id) }}">Editar</a>
                                    </div>                                      
                                    
                                </td>
                            </tr> 
                            @endforeach                                                  
                        </tbody>
                      </table>
                      <div class="row justify-content-md-center">
                            {{ $categorias->links() }}
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/categoria/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row justify-content-between">
                        <div class="col-4">Detalhe da categoria</div>
                        <div class="col-2">
                            <div class="row">
                                <div class="col-4">
                                    <a class="btn btn-success btn-sm" href="{{ route('categorias.index') }}"> Voltar</a>
                                </div>
                                <div class="col-4">
                                    <a class="btn btn-primary btn-sm" href="{{ route('categorias.edit', $categoria->id) }}"> Editar</a>
                                </div>
                            </div>                            
                        </div>
                    </div>                    
                </div>
                {{-- card-body--}}
                <div class="card-body">                        
                            <div class="row">
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Título:</strong>
                                        {{ $categoria->titulo }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Status:</strong>
                                        {{ $categoria->status }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                    <div class="form-group">
                                        <strong>Descrição:</strong>
                                        {{ $categoria->descricao }}
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Data Criação:</strong>
                                            {{ $categoria->created_at->format('d/m/Y h:m:s') }}
                                        </div>
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-12">
                                        <div class="form-group">
                                            <strong>Data da ultima atualização:</strong>
                                            {{ $categoria->updated_at->format('d/m/Y h:m:s') }}
                                        </div>
                                </div>
                            </div>
                </div>
                {{-- end card-body --}}
            </div>
        </div>
    </div>
</div>
@endsection